TABLE_POKEMON_INFO = { 

["Bulbasaur"] = {dexID = "#001", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Ivysaur"] = {dexID = "#002", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Venusaur"] = {dexID = "#003", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Charmander"] = {dexID = "#004", type1 = "Fire", type2 = "", background = "Fire"},
["Charmeleon"] = {dexID = "#005", type1 = "Fire", type2 = "", background = "Fire"},
["Charizard"] = {dexID = "#006", type1 = "Fire", type2 = "Fly", background = "Fire"},
["Squirtle"] = {dexID = "#007", type1 = "Water", type2 = "", background = "Water"},
["Wartortle"] = {dexID = "#008", type1 = "Water", type2 = "", background = "Water"},
["Blastoise"] = {dexID = "#009", type1 = "Water", type2 = "", background = "Water"},
["Caterpie"] = {dexID = "#010", type1 = "Bug", type2 = "", background = "Bug"},
["Metapod"] = {dexID = "#011", type1 = "Bug", type2 = "", background = "Bug"},
["Butterfree"] = {dexID = "#012", type1 = "Bug", type2 = "Fly", background = "Bug"},
["Weedle"] = {dexID = "#013", type1 = "Bug", type2 = "Poison", background = "Bug"},
["Kakuna"] = {dexID = "#014", type1 = "Bug", type2 = "Poison", background = "Bug"},
["Beedrill"] = {dexID = "#015", type1 = "Bug", type2 = "Poison", background = "Bug"},
["Pidgey"] = {dexID = "#016", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Pidgeotto"] = {dexID = "#017", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Pidgeot"] = {dexID = "#018", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Rattata"] = {dexID = "#019", type1 = "Normal", type2 = "", background = "Normal"},
["Raticate"] = {dexID = "#020", type1 = "Normal", type2 = "", background = "Normal"},
["Spearow"] = {dexID = "#021", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Fearow"] = {dexID = "#022", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Ekans"] = {dexID = "#023", type1 = "Poison", type2 = "", background = "Poison"},
["Arbok"] = {dexID = "#024", type1 = "Poison", type2 = "", background = "Poison"},
["Pikachu"] = {dexID = "#025", type1 = "Electric", type2 = "", background = "Electric"},
["Raichu"] = {dexID = "#026", type1 = "Electric", type2 = "", background = "Electric"},
["Sandshrew"] = {dexID = "#027", type1 = "Ground", type2 = "", background = "Ground"},
["Sandslash"] = {dexID = "#028", type1 = "Ground", type2 = "", background = "Ground"},
["Nidorana"] = {dexID = "#029", type1 = "Poison", type2 = "", background = "Poison"},
["Nidorina"] = {dexID = "#030", type1 = "Poison", type2 = "", background = "Poison"},
["Nidoqueen"] = {dexID = "#031", type1 = "Poison", type2 = "Ground", background = "Poison"},
["Nidorano"] = {dexID = "#032", type1 = "Poison", type2 = "", background = "Poison"},
["Nidorino"] = {dexID = "#033", type1 = "Poison", type2 = "", background = "Poison"},
["Nidoking"] = {dexID = "#034", type1 = "Poison", type2 = "Ground", background = "Poison"},
["Clefairy"] = {dexID = "#035", type1 = "Fairy", type2 = "", background = "Fairy"},
["Clefable"] = {dexID = "#036", type1 = "Fairy", type2 = "", background = "Fairy"},
["Vulpix"] = {dexID = "#037", type1 = "Fire", type2 = "", background = "Fire"},
["Ninetales"] = {dexID = "#038", type1 = "Fire", type2 = "", background = "Fire"},
["Jigglypuff"] = {dexID = "#039", type1 = "Normal", type2 = "Fairy", background = "Fairy"},
["Wigglytuff"] = {dexID = "#040", type1 = "Normal", type2 = "Fairy", background = "Fairy"},
["Zubat"] = {dexID = "#041", type1 = "Poison", type2 = "Fly", background = "Poison"},
["Golbat"] = {dexID = "#042", type1 = "Poison", type2 = "Fly", background = "Poison"},
["Oddish"] = {dexID = "#043", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Gloom"] = {dexID = "#044", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Vileplume"] = {dexID = "#045", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Paras"] = {dexID = "#046", type1 = "Bug", type2 = "Grass", background = "Bug"},
["Parasect"] = {dexID = "#047", type1 = "Bug", type2 = "Grass", background = "Bug"},
["Venonat"] = {dexID = "#048", type1 = "Bug", type2 = "Poison", background = "Bug"},
["Venomoth"] = {dexID = "#049", type1 = "Bug", type2 = "Poison", background = "Bug"},
["Diglett"] = {dexID = "#050", type1 = "Ground", type2 = "", background = "Ground"},
["Dugtrio"] = {dexID = "#051", type1 = "Ground", type2 = "", background = "Ground"},
["Meowth"] = {dexID = "#052", type1 = "Normal", type2 = "", background = "Normal"},
["Persian"] = {dexID = "#053", type1 = "Normal", type2 = "", background = "Normal"},
["Psyduck"] = {dexID = "#054", type1 = "Water", type2 = "", background = "Water"},
["Golduck"] = {dexID = "#055", type1 = "Water", type2 = "", background = "Water"},
["Mankey"] = {dexID = "#056", type1 = "Fighting", type2 = "", background = "Fighting"},
["Primeape"] = {dexID = "#057", type1 = "Fighting", type2 = "", background = "Fighting"},
["Growlithe"] = {dexID = "#058", type1 = "Fire", type2 = "", background = "Fire"},
["Arcanine"] = {dexID = "#059", type1 = "Fire", type2 = "", background = "Fire"},
["Poliwag"] = {dexID = "#060", type1 = "Water", type2 = "", background = "Water"},
["Poliwhirl"] = {dexID = "#061", type1 = "Water", type2 = "", background = "Water"},
["Poliwrath"] = {dexID = "#062", type1 = "Water", type2 = "Fighting", background = "Water"},
["Abra"] = {dexID = "#063", type1 = "Psychic", type2 = "", background = "Psychic"},
["Kadabra"] = {dexID = "#064", type1 = "Psychic", type2 = "", background = "Psychic"},
["Alakazam"] = {dexID = "#065", type1 = "Psychic", type2 = "", background = "Psychic"},
["Machop"] = {dexID = "#066", type1 = "Fighting", type2 = "", background = "Fighting"},
["Machoke"] = {dexID = "#067", type1 = "Fighting", type2 = "", background = "Fighting"},
["Machamp"] = {dexID = "#068", type1 = "Fighting", type2 = "", background = "Fighting"},
["Bellsprout"] = {dexID = "#069", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Weepinbell"] = {dexID = "#070", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Victreebel"] = {dexID = "#071", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Tentacool"] = {dexID = "#072", type1 = "Water", type2 = "Poison", background = "Water"},
["Tentacruel"] = {dexID = "#073", type1 = "Water", type2 = "Poison", background = "Water"},
["Geodude"] = {dexID = "#074", type1 = "Rock", type2 = "Ground", background = "Rock"},
["Graveler"] = {dexID = "#075", type1 = "Rock", type2 = "Ground", background = "Rock"},
["Golem"] = {dexID = "#076", type1 = "Rock", type2 = "Ground", background = "Rock"},
["Ponyta"] = {dexID = "#077", type1 = "Fire", type2 = "", background = "Fire"},
["Rapidash"] = {dexID = "#078", type1 = "Fire", type2 = "", background = "Fire"},
["Slowpoke"] = {dexID = "#079", type1 = "Water", type2 = "Psychic", background = "Water"},
["Slowbro"] = {dexID = "#080", type1 = "Water", type2 = "Psychic", background = "Water"},
["Magnemite"] = {dexID = "#081", type1 = "Electric", type2 = "Steel", background = "Electric"},
["Magneton"] = {dexID = "#082", type1 = "Electric", type2 = "Steel", background = "Electric"},
["Farfetchd"] = {dexID = "#083", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Doduo"] = {dexID = "#084", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Dodrio"] = {dexID = "#085", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Seel"] = {dexID = "#086", type1 = "Water", type2 = "", background = "Water"},
["Wewgong"] = {dexID = "#087", type1 = "Water", type2 = "Ice", background = "Water"},
["Grimer"] = {dexID = "#088", type1 = "Poison", type2 = "", background = "Poison"},
["Muk"] = {dexID = "#089", type1 = "Poison", type2 = "", background = "Poison"},
["Shellder"] = {dexID = "#090", type1 = "Water", type2 = "", background = "Water"},
["Cloyster"] = {dexID = "#091", type1 = "Water", type2 = "Ice", background = "Water"},
["Gastly"] = {dexID = "#092", type1 = "Ghost", type2 = "Poison", background = "Ghost"},
["Haunter"] = {dexID = "#093", type1 = "Ghost", type2 = "Poison", background = "Ghost"},
["Gengar"] = {dexID = "#094", type1 = "Ghost", type2 = "Poison", background = "Ghost"},
["Onix"] = {dexID = "#095", type1 = "Rock", type2 = "Ground", background = "Rock"},
["Drowzee"] = {dexID = "#096", type1 = "Psychic", type2 = "", background = "Psychic"},
["Hypno"] = {dexID = "#097", type1 = "Psychic", type2 = "", background = "Psychic"},
["Krabby"] = {dexID = "#098", type1 = "Water", type2 = "", background = "Water"},
["Kingler"] = {dexID = "#099", type1 = "Water", type2 = "", background = "Water"},
["Voltorb"] = {dexID = "#100", type1 = "Electric", type2 = "", background = "Electric"},
["Electrode"] = {dexID = "#101", type1 = "Electric", type2 = "", background = "Electric"},
["Exeggcute"] = {dexID = "#102", type1 = "Grass", type2 = "Psychic", background = "Grass"},
["Exeggutor"] = {dexID = "#103", type1 = "Grass", type2 = "Psychic", background = "Grass"},
["Cubone"] = {dexID = "#104", type1 = "Ground", type2 = "", background = "Ground"},
["Marowak"] = {dexID = "#105", type1 = "Ground", type2 = "", background = "Ground"},
["Hitmonlee"] = {dexID = "#106", type1 = "Fighting", type2 = "", background = "Fighting"},
["Hitmonchan"] = {dexID = "#107", type1 = "Fighting", type2 = "", background = "Fighting"},
["Lickitung"] = {dexID = "#108", type1 = "Normal", type2 = "", background = "Normal"},
["Koffing"] = {dexID = "#109", type1 = "Poison", type2 = "", background = "Poison"},
["Weezing"] = {dexID = "#110", type1 = "Poison", type2 = "", background = "Poison"},
["Rhyhorn"] = {dexID = "#111", type1 = "Ground", type2 = "Rock", background = "Ground"},
["Rhydon"] = {dexID = "#112", type1 = "Ground", type2 = "Rock", background = "Ground"},
["Chansey"] = {dexID = "#113", type1 = "Normal", type2 = "", background = "Normal"},
["Tangela"] = {dexID = "#114", type1 = "Grass", type2 = "", background = "Grass"},
["Kangaskhan"] = {dexID = "#115", type1 = "Normal", type2 = "", background = "Normal"},
["Horsea"] = {dexID = "#116", type1 = "Water", type2 = "", background = "Water"},
["Seadra"] = {dexID = "#117", type1 = "Water", type2 = "", background = "Water"},
["Goldeen"] = {dexID = "#118", type1 = "Water", type2 = "", background = "Water"},
["Seaking"] = {dexID = "#119", type1 = "Water", type2 = "", background = "Water"},
["Staryu"] = {dexID = "#120", type1 = "Water", type2 = "", background = "Water"},
["Starmie"] = {dexID = "#121", type1 = "Water", type2 = "Psychic", background = "Water"},
["Mr. Mime"] = {dexID = "#122", type1 = "Psychic", type2 = "Fairy", background = "Psychic"},
["Scyther"] = {dexID = "#123", type1 = "Bug", type2 = "Fly", background = "Bug"},
["Jynx"] = {dexID = "#124", type1 = "Ice", type2 = "Psychic", background = "Ice"},
["Electabuzz"] = {dexID = "#125", type1 = "Electric", type2 = "", background = "Electric"},
["Magmar"] = {dexID = "#126", type1 = "Fire", type2 = "", background = "Fire"},
["Pinsir"] = {dexID = "#127", type1 = "Bug", type2 = "", background = "Bug"},
["Tauros"] = {dexID = "#128", type1 = "Normal", type2 = "", background = "Normal"},
["Magikarp"] = {dexID = "#129", type1 = "Water", type2 = "", background = "Water"},
["Gyarados"] = {dexID = "#130", type1 = "Water", type2 = "Fly", background = "Water"},
["Lapras"] = {dexID = "#131", type1 = "Water", type2 = "Ice", background = "Ice"},
["Ditto"] = {dexID = "#132", type1 = "Normal", type2 = "", background = "Normal"},
["Eevee"] = {dexID = "#133", type1 = "Normal", type2 = "", background = "Normal"},
["Vaporeon"] = {dexID = "#134", type1 = "Water", type2 = "", background = "Water"},
["Jolteon"] = {dexID = "#135", type1 = "Electric", type2 = "", background = "Electric"},
["Flareon"] = {dexID = "#136", type1 = "Fire", type2 = "", background = "Fire"},
["Porygon"] = {dexID = "#137", type1 = "Normal", type2 = "", background = "Normal"},
["Omanyte"] = {dexID = "#138", type1 = "Rock", type2 = "Water", background = "Water"},
["Omastar"] = {dexID = "#139", type1 = "Rock", type2 = "Water", background = "Water"},
["Kabuto"] = {dexID = "#140", type1 = "Rock", type2 = "Water", background = "Water"},
["Kabutops"] = {dexID = "#141", type1 = "Rock", type2 = "Water", background = "Water"},
["Aerodactyl"] = {dexID = "#142", type1 = "Rock", type2 = "Fly", background = "Rock"},
["Snorlax"] = {dexID = "#143", type1 = "Normal", type2 = "", background = "Normal"},
["Articuno"] = {dexID = "#144", type1 = "Ice", type2 = "Fly", background = "Ice"},
["Zapdos"] = {dexID = "#145", type1 = "Electric", type2 = "Fly", background = "Electric"},
["Moltres"] = {dexID = "#146", type1 = "Fire", type2 = "Fly", background = "Fire"},
["Dratini"] = {dexID = "#147", type1 = "Dragon", type2 = "", background = "Dragon"},
["Dragonair"] = {dexID = "#148", type1 = "Dragon", type2 = "", background = "Dragon"},
["Dragonite"] = {dexID = "#149", type1 = "Dragon", type2 = "Fly", background = "Dragon"},
["Mewtwo"] = {dexID = "#150", type1 = "Psychic", type2 = "", background = "Psychic"},
["Mew"] = {dexID = "#151", type1 = "Psychic", type2 = "", background = "Psychic"},

["Shiny Bulbasaur"] = {dexID = "#001", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Shiny Ivysaur"] = {dexID = "#002", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Shiny Venusaur"] = {dexID = "#003", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Shiny Charmander"] = {dexID = "#004", type1 = "Fire", type2 = "", background = "Fire"},
["Shiny Charmeleon"] = {dexID = "#005", type1 = "Fire", type2 = "", background = "Fire"},
["Shiny Charizard"] = {dexID = "#006", type1 = "Fire", type2 = "Fly", background = "Fire"},
["Shiny Squirtle"] = {dexID = "#007", type1 = "Water", type2 = "", background = "Water"},
["Shiny Wartortle"] = {dexID = "#008", type1 = "Water", type2 = "", background = "Water"},
["Shiny Blastoise"] = {dexID = "#009", type1 = "Water", type2 = "", background = "Water"},
["Shiny Caterpie"] = {dexID = "#010", type1 = "Bug", type2 = "", background = "Bug"},
["Shiny Metapod"] = {dexID = "#011", type1 = "Bug", type2 = "", background = "Bug"},
["Shiny Butterfree"] = {dexID = "#012", type1 = "Bug", type2 = "Fly", background = "Bug"},
["Shiny Weedle"] = {dexID = "#013", type1 = "Bug", type2 = "Poison", background = "Bug"},
["Shiny Kakuna"] = {dexID = "#014", type1 = "Bug", type2 = "Poison", background = "Bug"},
["Shiny Beedrill"] = {dexID = "#015", type1 = "Bug", type2 = "Poison", background = "Bug"},
["Shiny Pidgey"] = {dexID = "#016", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Shiny Pidgeotto"] = {dexID = "#017", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Shiny Pidgeot"] = {dexID = "#018", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Shiny Rattata"] = {dexID = "#019", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Raticate"] = {dexID = "#020", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Spearow"] = {dexID = "#021", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Shiny Fearow"] = {dexID = "#022", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Shiny Ekans"] = {dexID = "#023", type1 = "Poison", type2 = "", background = "Poison"},
["Shiny Arbok"] = {dexID = "#024", type1 = "Poison", type2 = "", background = "Poison"},
["Shiny Pikachu"] = {dexID = "#025", type1 = "Electric", type2 = "", background = "Electric"},
["Shiny Raichu"] = {dexID = "#026", type1 = "Electric", type2 = "", background = "Electric"},
["Shiny Sandshrew"] = {dexID = "#027", type1 = "Ground", type2 = "", background = "Ground"},
["Shiny Sandslash"] = {dexID = "#028", type1 = "Ground", type2 = "", background = "Ground"},
["Shiny Nidorana"] = {dexID = "#029", type1 = "Poison", type2 = "", background = "Poison"},
["Shiny Nidorina"] = {dexID = "#030", type1 = "Poison", type2 = "", background = "Poison"},
["Shiny Nidoqueen"] = {dexID = "#031", type1 = "Poison", type2 = "Ground", background = "Poison"},
["Shiny Nidorano"] = {dexID = "#032", type1 = "Poison", type2 = "", background = "Poison"},
["Shiny Nidorino"] = {dexID = "#033", type1 = "Poison", type2 = "", background = "Poison"},
["Shiny Nidoking"] = {dexID = "#034", type1 = "Poison", type2 = "Ground", background = "Poison"},
["Shiny Clefairy"] = {dexID = "#035", type1 = "Fairy", type2 = "", background = "Fairy"},
["Shiny Clefable"] = {dexID = "#036", type1 = "Fairy", type2 = "", background = "Fairy"},
["Shiny Vulpix"] = {dexID = "#037", type1 = "Fire", type2 = "", background = "Fire"},
["Shiny Ninetales"] = {dexID = "#038", type1 = "Fire", type2 = "", background = "Fire"},
["Shiny Jigglypuff"] = {dexID = "#039", type1 = "Normal", type2 = "Fairy", background = "Fairy"},
["Shiny Wigglytuff"] = {dexID = "#040", type1 = "Normal", type2 = "Fairy", background = "Fairy"},
["Shiny Zubat"] = {dexID = "#041", type1 = "Poison", type2 = "Fly", background = "Poison"},
["Shiny Golbat"] = {dexID = "#042", type1 = "Poison", type2 = "Fly", background = "Poison"},
["Shiny Oddish"] = {dexID = "#043", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Shiny Gloom"] = {dexID = "#044", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Shiny Vileplume"] = {dexID = "#045", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Shiny Paras"] = {dexID = "#046", type1 = "Bug", type2 = "Grass", background = "Bug"},
["Shiny Parasect"] = {dexID = "#047", type1 = "Bug", type2 = "Grass", background = "Bug"},
["Shiny Venonat"] = {dexID = "#048", type1 = "Bug", type2 = "Poison", background = "Bug"},
["Shiny Venomoth"] = {dexID = "#049", type1 = "Bug", type2 = "Poison", background = "Bug"},
["Shiny Diglett"] = {dexID = "#050", type1 = "Ground", type2 = "", background = "Ground"},
["Shiny Dugtrio"] = {dexID = "#051", type1 = "Ground", type2 = "", background = "Ground"},
["Shiny Meowth"] = {dexID = "#052", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Persian"] = {dexID = "#053", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Psyduck"] = {dexID = "#054", type1 = "Water", type2 = "", background = "Water"},
["Shiny Golduck"] = {dexID = "#055", type1 = "Water", type2 = "", background = "Water"},
["Shiny Mankey"] = {dexID = "#056", type1 = "Fighting", type2 = "", background = "Fighting"},
["Shiny Primeape"] = {dexID = "#057", type1 = "Fighting", type2 = "", background = "Fighting"},
["Shiny Growlithe"] = {dexID = "#058", type1 = "Fire", type2 = "", background = "Fire"},
["Shiny Arcanine"] = {dexID = "#059", type1 = "Fire", type2 = "", background = "Fire"},
["Shiny Poliwag"] = {dexID = "#060", type1 = "Water", type2 = "", background = "Water"},
["Shiny Poliwhirl"] = {dexID = "#061", type1 = "Water", type2 = "", background = "Water"},
["Shiny Poliwrath"] = {dexID = "#062", type1 = "Water", type2 = "Fighting", background = "Water"},
["Shiny Abra"] = {dexID = "#063", type1 = "Psychic", type2 = "", background = "Psychic"},
["Shiny Kadabra"] = {dexID = "#064", type1 = "Psychic", type2 = "", background = "Psychic"},
["Shiny Alakazam"] = {dexID = "#065", type1 = "Psychic", type2 = "", background = "Psychic"},
["Shiny Machop"] = {dexID = "#066", type1 = "Fighting", type2 = "", background = "Fighting"},
["Shiny Machoke"] = {dexID = "#067", type1 = "Fighting", type2 = "", background = "Fighting"},
["Shiny Machamp"] = {dexID = "#068", type1 = "Fighting", type2 = "", background = "Fighting"},
["Shiny Bellsprout"] = {dexID = "#069", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Shiny Weepinbell"] = {dexID = "#070", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Shiny Victreebel"] = {dexID = "#071", type1 = "Grass", type2 = "Poison", background = "Grass"},
["Shiny Tentacool"] = {dexID = "#072", type1 = "Water", type2 = "Poison", background = "Water"},
["Shiny Tentacruel"] = {dexID = "#073", type1 = "Water", type2 = "Poison", background = "Water"},
["Shiny Geodude"] = {dexID = "#074", type1 = "Rock", type2 = "Ground", background = "Rock"},
["Shiny Graveler"] = {dexID = "#075", type1 = "Rock", type2 = "Ground", background = "Rock"},
["Shiny Golem"] = {dexID = "#076", type1 = "Rock", type2 = "Ground", background = "Rock"},
["Shiny Ponyta"] = {dexID = "#077", type1 = "Fire", type2 = "", background = "Fire"},
["Shiny Rapidash"] = {dexID = "#078", type1 = "Fire", type2 = "", background = "Fire"},
["Shiny Slowpoke"] = {dexID = "#079", type1 = "Water", type2 = "Psychic", background = "Water"},
["Shiny Slowbro"] = {dexID = "#080", type1 = "Water", type2 = "Psychic", background = "Water"},
["Shiny Magnemite"] = {dexID = "#081", type1 = "Electric", type2 = "Steel", background = "Electric"},
["Shiny Magneton"] = {dexID = "#082", type1 = "Electric", type2 = "Steel", background = "Electric"},
["Shiny Farfetchd"] = {dexID = "#083", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Shiny Doduo"] = {dexID = "#084", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Shiny Dodrio"] = {dexID = "#085", type1 = "Normal", type2 = "Fly", background = "Fly"},
["Shiny Seel"] = {dexID = "#086", type1 = "Water", type2 = "", background = "Water"},
["Shiny Wewgong"] = {dexID = "#087", type1 = "Water", type2 = "Ice", background = "Water"},
["Shiny Grimer"] = {dexID = "#088", type1 = "Poison", type2 = "", background = "Poison"},
["Shiny Muk"] = {dexID = "#089", type1 = "Poison", type2 = "", background = "Poison"},
["Shiny Shellder"] = {dexID = "#090", type1 = "Water", type2 = "", background = "Water"},
["Shiny Cloyster"] = {dexID = "#091", type1 = "Water", type2 = "Ice", background = "Water"},
["Shiny Gastly"] = {dexID = "#092", type1 = "Ghost", type2 = "Poison", background = "Ghost"},
["Shiny Haunter"] = {dexID = "#093", type1 = "Ghost", type2 = "Poison", background = "Ghost"},
["Shiny Gengar"] = {dexID = "#094", type1 = "Ghost", type2 = "Poison", background = "Ghost"},
["Shiny Onix"] = {dexID = "#095", type1 = "Rock", type2 = "Ground", background = "Rock"},
["Shiny Drowzee"] = {dexID = "#096", type1 = "Psychic", type2 = "", background = "Psychic"},
["Shiny Hypno"] = {dexID = "#097", type1 = "Psychic", type2 = "", background = "Psychic"},
["Shiny Krabby"] = {dexID = "#098", type1 = "Water", type2 = "", background = "Water"},
["Shiny Kingler"] = {dexID = "#099", type1 = "Water", type2 = "", background = "Water"},
["Shiny Voltorb"] = {dexID = "#100", type1 = "Electric", type2 = "", background = "Electric"},
["Shiny Electrode"] = {dexID = "#101", type1 = "Electric", type2 = "", background = "Electric"},
["Shiny Exeggcute"] = {dexID = "#102", type1 = "Grass", type2 = "Psychic", background = "Grass"},
["Shiny Exeggutor"] = {dexID = "#103", type1 = "Grass", type2 = "Psychic", background = "Grass"},
["Shiny Cubone"] = {dexID = "#104", type1 = "Ground", type2 = "", background = "Ground"},
["Shiny Marowak"] = {dexID = "#105", type1 = "Ground", type2 = "", background = "Ground"},
["Shiny Hitmonlee"] = {dexID = "#106", type1 = "Fighting", type2 = "", background = "Fighting"},
["Shiny Hitmonchan"] = {dexID = "#107", type1 = "Fighting", type2 = "", background = "Fighting"},
["Shiny Lickitung"] = {dexID = "#108", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Koffing"] = {dexID = "#109", type1 = "Poison", type2 = "", background = "Poison"},
["Shiny Weezing"] = {dexID = "#110", type1 = "Poison", type2 = "", background = "Poison"},
["Shiny Rhyhorn"] = {dexID = "#111", type1 = "Ground", type2 = "Rock", background = "Ground"},
["Shiny Rhydon"] = {dexID = "#112", type1 = "Ground", type2 = "Rock", background = "Ground"},
["Shiny Chansey"] = {dexID = "#113", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Tangela"] = {dexID = "#114", type1 = "Grass", type2 = "", background = "Grass"},
["Shiny Kangaskhan"] = {dexID = "#115", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Horsea"] = {dexID = "#116", type1 = "Water", type2 = "", background = "Water"},
["Shiny Seadra"] = {dexID = "#117", type1 = "Water", type2 = "", background = "Water"},
["Shiny Goldeen"] = {dexID = "#118", type1 = "Water", type2 = "", background = "Water"},
["Shiny Seaking"] = {dexID = "#119", type1 = "Water", type2 = "", background = "Water"},
["Shiny Staryu"] = {dexID = "#120", type1 = "Water", type2 = "", background = "Water"},
["Shiny Starmie"] = {dexID = "#121", type1 = "Water", type2 = "Psychic", background = "Water"},
["Shiny Mr. mime"] = {dexID = "#122", type1 = "Psychic", type2 = "Fairy", background = "Psychic"},
["Shiny Scyther"] = {dexID = "#123", type1 = "Bug", type2 = "Fly", background = "Bug"},
["Shiny Jynx"] = {dexID = "#124", type1 = "Ice", type2 = "Psychic", background = "Ice"},
["Shiny Electabuzz"] = {dexID = "#125", type1 = "Electric", type2 = "", background = "Electric"},
["Shiny Magmar"] = {dexID = "#126", type1 = "Fire", type2 = "", background = "Fire"},
["Shiny Pinsir"] = {dexID = "#127", type1 = "Bug", type2 = "", background = "Bug"},
["Shiny Tauros"] = {dexID = "#128", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Magikarp"] = {dexID = "#129", type1 = "Water", type2 = "", background = "Water"},
["Shiny Gyarados"] = {dexID = "#130", type1 = "Water", type2 = "Fly", background = "Water"},
["Shiny Lapras"] = {dexID = "#131", type1 = "Water", type2 = "Ice", background = "Ice"},
["Shiny Ditto"] = {dexID = "#132", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Eevee"] = {dexID = "#133", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Vaporeon"] = {dexID = "#134", type1 = "Water", type2 = "", background = "Water"},
["Shiny Jolteon"] = {dexID = "#135", type1 = "Electric", type2 = "", background = "Electric"},
["Shiny Flareon"] = {dexID = "#136", type1 = "Fire", type2 = "", background = "Fire"},
["Shiny Porygon"] = {dexID = "#137", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Omanyte"] = {dexID = "#138", type1 = "Rock", type2 = "Water", background = "Water"},
["Shiny Omastar"] = {dexID = "#139", type1 = "Rock", type2 = "Water", background = "Water"},
["Shiny Kabuto"] = {dexID = "#140", type1 = "Rock", type2 = "Water", background = "Water"},
["Shiny Kabutops"] = {dexID = "#141", type1 = "Rock", type2 = "Water", background = "Water"},
["Shiny Aerodactyl"] = {dexID = "#142", type1 = "Rock", type2 = "Fly", background = "Rock"},
["Shiny Snorlax"] = {dexID = "#143", type1 = "Normal", type2 = "", background = "Normal"},
["Shiny Articuno"] = {dexID = "#144", type1 = "Ice", type2 = "Fly", background = "Ice"},
["Shiny Zapdos"] = {dexID = "#145", type1 = "Electric", type2 = "Fly", background = "Electric"},
["Shiny Moltres"] = {dexID = "#146", type1 = "Fire", type2 = "Fly", background = "Fire"},
["Shiny Dratini"] = {dexID = "#147", type1 = "Dragon", type2 = "", background = "Dragon"},
["Shiny Dragonair"] = {dexID = "#148", type1 = "Dragon", type2 = "", background = "Dragon"},
["Shiny Dragonite"] = {dexID = "#149", type1 = "Dragon", type2 = "Fly", background = "Dragon"},
["Shiny Mewtwo"] = {dexID = "#150", type1 = "Psychic", type2 = "", background = "Psychic"},
["Shiny Mew"] = {dexID = "#151", type1 = "Psychic", type2 = "", background = "Psychic"},
}

NATURES_INFO = {
["Adamant"] = {Increase = "Attack", Decrease = "Sp. Atk"},
["Bashful"] = {Increase = "	Sp. Atk", Decrease = "Sp. Atk"},
["Bold"] = {Increase = "Defense", Decrease = "Attack"},
["Brave"] = {Increase = "Attack", Decrease = "Speed"},
["Calm"] = {Increase = "Sp. Def", Decrease = "Attack"},
["Careful"] = {Increase = "Sp. Def", Decrease = "Sp. Atk"},
["Docile"] = {Increase = "Defense", Decrease = "Defense"},
["Gentle"] = {Increase = "Sp. Def", Decrease = "Defense"},
["Hardy"] = {Increase = "Attack", Decrease = "Attack"},
["Hasty"] = {Increase = "Speed", Decrease = "Defense"},
["Impish"] = {Increase = "Defense", Decrease = "Sp. Atk"},
["Jolly"] = {Increase = "Speed", Decrease = "Sp. Atk"},
["Lax"] = {Increase = "Defense", Decrease = "Sp. Def"},
["Lonely"] = {Increase = "Attack", Decrease = "Defense"},
["Mild"] = {Increase = "Sp. Atk", Decrease = "Defense"},
["Modest"] = {Increase = "Sp. Atk", Decrease = "Attack"},
["Naive"] = {Increase = "Speed", Decrease = "Sp. Def"},
["Naughty"] = {Increase = "Attack", Decrease = "Sp. Def"},
["Quiet"] = {Increase = "Sp. Atk", Decrease = "Speed"},
["Quirky"] = {Increase = "Sp. Def", Decrease = "Sp. Def"},
["Rash"] = {Increase = "Sp. Atk", Decrease = "Sp. Def"},
["Relaxed"] = {Increase = "Defense", Decrease = "Speed"},
["Sassy"] = {Increase = "Sp. Def", Decrease = "Speed"},
["Serious"] = {Increase = "Speed", Decrease = "Speed"},
["Timid"] = {Increase = "Speed", Decrease = "Attack"},
}